---
permalink: /admin/config.yml
---

backend:
  name: git-gateway
  branch: master

media_folder: "assets/images"

collections:
  {% for collection_hash in site.data.collections -%}
    {%- assign collection = collection_hash[1] -%}
    - {{ collection | jsonify }}
  {% endfor %}
