---
permalink: /admin/config.yml
---

backend:
  name: git-gateway
  branch: master

media_folder: "assets/images"

collections:
  - {{ site.data.collections.homework | jsonify }}
  - {{ site.data.collections.lessons | jsonify }}
  - {{ site.data.collections.meetings | jsonify }}
  - {{ site.data.collections.projects | jsonify }}
  - {{ site.data.collections.resources | jsonify }}
  - {{ site.data.collections.topics | jsonify }}
  - {{ site.data.collections.units | jsonify }}
